version: "3.5"
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=easyappointments
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=easyappointments
    
    expose:
      - 3306

  server:
    build: ./server
    image: easyappointments-server:v1
    expose:
      - 80
    volumes:
      - ../:/var/www/html
      - ./server/config.php:/var/www/html/config.php:ro
      - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
