name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '16.19'
      
      - name: Install NodeJS dependencies
        run: npm install
  
      - name: Install PHP dependencies
        run: composer install
        
      - name: Build
        run: npm run build